name: mineru2.5
channels:
  - conda-forge
  - defaults
dependencies:
  - backports.asyncio.runner=1.2.0=pyh5ded981_2
  - backports.zstd=1.3.0=py312h06d0912_0
  - brotli-python=1.2.0=py312hc6d9e41_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2026.1.4=h4c7d964_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py312he06e257_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cryptography=46.0.3=py312h232196e_1
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - expat=2.7.3=h885b0b7_4
  - ghostscript=10.06.0=hac47afa_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - leptonica=1.83.1=he4e1813_5
  - lerc=4.0.0=h6470a55_1
  - libarchive=3.7.7=h88ece9c_0
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=3.1.2=hfd05255_0
  - libpng=1.6.54=h7351971_0
  - libsqlite=3.51.2=hf5d6505_0
  - libtiff=4.7.0=hfc51747_1
  - libwebp=1.6.0=h4d5522a_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=hcfcfb64_0
  - lzo=2.10=h6a83c73_1002
  - msal=1.34.0=pyhd8ed1ab_0
  - openjpeg=2.5.3=h24db6dd_1
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pip=25.3=pyhc872135_0
  - pluggy=1.6.0=pyhf9edf01_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh09c184e_7
  - pytest=9.0.2=pyhcf101f3_0
  - pytest-asyncio=1.3.0=pyhcf101f3_0
  - python=3.12.7=hce54a09_0_cpython
  - python_abi=3.12=8_cp312
  - requests=2.32.5=pyhcf101f3_1
  - sqlite=3.51.0=hda9a48d_0
  - tesseract=5.5.1=h86caa34_0
  - tk=8.6.15=hf199647_0
  - tomli=2.4.0=pyhcf101f3_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py312haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h534d264_6
  - pip:
      - accelerate==1.12.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anthropic==0.71.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - astor==0.8.1
      - attrs==25.4.0
      - av==16.0.1
      - azure-ai-textanalytics==5.3.0
      - azure-cognitiveservices-vision-computervision==0.9.0
      - azure-common==1.1.28
      - azure-core==1.37.0
      - azure-identity==1.15.0
      - azure-storage-blob==12.19.0
      - beautifulsoup4==4.14.3
      - blake3==1.0.8
      - boto3==1.42.21
      - botocore==1.42.21
      - cachetools==6.2.3
      - cbor2==5.7.1
      - click==8.3.1
      - cloudpickle==3.1.2
      - coloredlogs==15.0.1
      - colorlog==6.10.1
      - compressed-tensors==0.12.2
      - contourpy==1.3.3
      - cycler==0.12.1
      - deprecated==1.3.1
      - deprecation==2.1.0
      - depyf==0.20.0
      - dill==0.4.0
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.8.0
      - doclayout-yolo==0.0.4
      - docstring-parser==0.17.0
      - einops==0.8.1
      - email-validator==2.3.0
      - fast-langdetect==0.2.5
      - fastapi==0.128.0
      - fastapi-cli==0.0.16
      - fastapi-cloud-cli==0.6.0
      - fastar==0.8.0
      - fasttext-predict==0.9.2.4
      - ffmpy==1.0.0
      - filelock==3.20.2
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - frozendict==2.4.7
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - ftfy==6.3.1
      - gguf==0.17.1
      - groovy==0.1.2
      - h11==0.16.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-retries==0.4.5
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - ijson==3.4.0.post0
      - imageio==2.37.2
      - img2pdf==0.6.3
      - interegular==0.3.3
      - isodate==0.7.2
      - jinja2==3.1.6
      - jiter==0.12.0
      - jmespath==1.0.1
      - json-repair==0.55.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lark==1.2.2
      - lazy-loader==0.4
      - llguidance==1.4.0
      - lm-format-enforcer==0.11.3
      - loguru==0.7.3
      - lxml==6.0.2
      - magika==1.0.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mcp==1.12.4
      - mdurl==0.1.2
      - mineru==2.7.1
      - mineru-vl-utils==0.1.19.1
      - mistral-common==1.8.6
      - model-hosting-container-standards==0.1.12
      - modelscope==1.33.0
      - mpmath==1.3.0
      - msal-extensions==1.3.1
      - msgspec==0.20.0
      - msrest==0.7.1
      - multidict==6.7.0
      - networkx==3.6.1
      - ninja==1.13.0
      - numpy==1.26.2
      - oauthlib==3.3.1
      - ocrmypdf==16.13.0
      - office365-rest-python-client==2.5.3
      - omegaconf==2.3.0
      - onnxruntime==1.20.1
      - openai==2.14.0
      - openai-harmony==0.0.8
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - orjson==3.11.5
      - outlines-core==0.2.11
      - pandas==2.1.3
      - partial-json-parser==0.2.1.1.post7
      - pdf2image==1.16.3
      - pdfminer-six==20260107
      - pdftext==0.6.3
      - pi-heif==1.1.1
      - pikepdf==10.2.0
      - pillow==12.1.0
      - polars==1.36.1
      - polars-runtime-32==1.36.1
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.4.1
      - protobuf==6.33.2
      - psutil==7.2.1
      - py-cpuinfo==9.0.0
      - pybase64==1.4.3
      - pyclipper==1.4.0
      - pycountry==24.6.1
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-extra-types==2.10.6
      - pydantic-settings==2.12.0
      - pydub==0.25.1
      - pymupdf==1.26.7
      - pyparsing==3.3.1
      - pypdf==6.5.0
      - pypdf2==3.0.1
      - pypdfium2==4.30.0
      - pyreadline3==3.5.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.21
      - pytz==2025.2
      - pywin32==311
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - qwen-vl-utils==0.0.14
      - referencing==0.37.0
      - regex==2025.11.3
      - reportlab==4.4.7
      - requests-oauthlib==2.0.0
      - rich==14.2.0
      - rich-toolkit==0.17.0
      - rignore==0.7.6
      - robust-downloader==0.0.2
      - rpds-py==0.30.0
      - ruff==0.14.10
      - s3transfer==0.16.0
      - safehttpx==0.1.7
      - safetensors==0.7.0
      - scikit-image==0.26.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.47.0
      - setproctitle==1.3.7
      - setuptools==79.0.1
      - shapely==2.1.2
      - shellingham==1.5.4
      - simsimd==6.5.12
      - six==1.17.0
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.8.1
      - soxr==1.0.0
      - sse-starlette==3.1.2
      - starlette==0.50.0
      - stringzilla==4.6.0
      - supervisor==4.3.0
      - sympy==1.14.0
      - thop==0.1.1-2209072238
      - tifffile==2025.12.20
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - tomlkit==0.13.3
      - torch==2.9.1
      - torchvision==0.24.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - typer==0.21.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - ultralytics==8.3.248
      - ultralytics-thop==2.0.18
      - urllib3==2.6.2
      - uv==0.9.21
      - uvicorn==0.24.0
      - watchfiles==1.1.1
      - wcwidth==0.2.14
      - websockets==15.0.1
      - win32-setctime==1.2.0
      - wrapt==2.0.1
      - xgrammar==0.1.29
      - yarl==1.22.0
